services:
  fsw:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: apazagab/fsw:demo
    volumes:
      - type: bind
        source: /home/gabe/repos/techleap/techleap-flight-software
        target: /app
      - type: bind
        source: /home/gabe/repos/techleap/basilisk/.
        target: /basilisk
    tty: true