services:
  fsw:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: apazagab/fsw:demo
    ports:
      - "5561:5561"
    volumes:
      - type: bind
        source: /home/gabe/repos/techleap/techleap-flight-software
        target: /app
      - type: bind
        source: /home/gabe/repos/gabe/basilisk/.
        target: /basilisk
      - type: bind
        source: /home/gabe/repos/techleap/techleap_software_workbench
        target: /software
    tty: true
    container_name: FSW