// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payloadmessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_payloadmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_payloadmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_payloadmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_payloadmessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_payloadmessage_2eproto;
namespace raven {
namespace fcu {
namespace swicd {
class RavenFCU_SWICD_PayloadMessage;
class RavenFCU_SWICD_PayloadMessageDefaultTypeInternal;
extern RavenFCU_SWICD_PayloadMessageDefaultTypeInternal _RavenFCU_SWICD_PayloadMessage_default_instance_;
}  // namespace swicd
}  // namespace fcu
}  // namespace raven
PROTOBUF_NAMESPACE_OPEN
template<> ::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage* Arena::CreateMaybeMessage<::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace raven {
namespace fcu {
namespace swicd {

// ===================================================================

class RavenFCU_SWICD_PayloadMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage) */ {
 public:
  inline RavenFCU_SWICD_PayloadMessage() : RavenFCU_SWICD_PayloadMessage(nullptr) {}
  virtual ~RavenFCU_SWICD_PayloadMessage();

  RavenFCU_SWICD_PayloadMessage(const RavenFCU_SWICD_PayloadMessage& from);
  RavenFCU_SWICD_PayloadMessage(RavenFCU_SWICD_PayloadMessage&& from) noexcept
    : RavenFCU_SWICD_PayloadMessage() {
    *this = ::std::move(from);
  }

  inline RavenFCU_SWICD_PayloadMessage& operator=(const RavenFCU_SWICD_PayloadMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline RavenFCU_SWICD_PayloadMessage& operator=(RavenFCU_SWICD_PayloadMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RavenFCU_SWICD_PayloadMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RavenFCU_SWICD_PayloadMessage* internal_default_instance() {
    return reinterpret_cast<const RavenFCU_SWICD_PayloadMessage*>(
               &_RavenFCU_SWICD_PayloadMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RavenFCU_SWICD_PayloadMessage& a, RavenFCU_SWICD_PayloadMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(RavenFCU_SWICD_PayloadMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RavenFCU_SWICD_PayloadMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RavenFCU_SWICD_PayloadMessage* New() const final {
    return CreateMaybeMessage<RavenFCU_SWICD_PayloadMessage>(nullptr);
  }

  RavenFCU_SWICD_PayloadMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RavenFCU_SWICD_PayloadMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RavenFCU_SWICD_PayloadMessage& from);
  void MergeFrom(const RavenFCU_SWICD_PayloadMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RavenFCU_SWICD_PayloadMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage";
  }
  protected:
  explicit RavenFCU_SWICD_PayloadMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_payloadmessage_2eproto);
    return ::descriptor_table_payloadmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kMessageSentTSFieldNumber = 1,
    kMessageReceivedTSFieldNumber = 2,
  };
  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // double messageSentTS = 1;
  void clear_messagesentts();
  double messagesentts() const;
  void set_messagesentts(double value);
  private:
  double _internal_messagesentts() const;
  void _internal_set_messagesentts(double value);
  public:

  // double messageReceivedTS = 2;
  void clear_messagereceivedts();
  double messagereceivedts() const;
  void set_messagereceivedts(double value);
  private:
  double _internal_messagereceivedts() const;
  void _internal_set_messagereceivedts(double value);
  public:

  // @@protoc_insertion_point(class_scope:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  double messagesentts_;
  double messagereceivedts_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_payloadmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RavenFCU_SWICD_PayloadMessage

// double messageSentTS = 1;
inline void RavenFCU_SWICD_PayloadMessage::clear_messagesentts() {
  messagesentts_ = 0;
}
inline double RavenFCU_SWICD_PayloadMessage::_internal_messagesentts() const {
  return messagesentts_;
}
inline double RavenFCU_SWICD_PayloadMessage::messagesentts() const {
  // @@protoc_insertion_point(field_get:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.messageSentTS)
  return _internal_messagesentts();
}
inline void RavenFCU_SWICD_PayloadMessage::_internal_set_messagesentts(double value) {
  
  messagesentts_ = value;
}
inline void RavenFCU_SWICD_PayloadMessage::set_messagesentts(double value) {
  _internal_set_messagesentts(value);
  // @@protoc_insertion_point(field_set:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.messageSentTS)
}

// double messageReceivedTS = 2;
inline void RavenFCU_SWICD_PayloadMessage::clear_messagereceivedts() {
  messagereceivedts_ = 0;
}
inline double RavenFCU_SWICD_PayloadMessage::_internal_messagereceivedts() const {
  return messagereceivedts_;
}
inline double RavenFCU_SWICD_PayloadMessage::messagereceivedts() const {
  // @@protoc_insertion_point(field_get:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.messageReceivedTS)
  return _internal_messagereceivedts();
}
inline void RavenFCU_SWICD_PayloadMessage::_internal_set_messagereceivedts(double value) {
  
  messagereceivedts_ = value;
}
inline void RavenFCU_SWICD_PayloadMessage::set_messagereceivedts(double value) {
  _internal_set_messagereceivedts(value);
  // @@protoc_insertion_point(field_set:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.messageReceivedTS)
}

// bytes data = 3;
inline void RavenFCU_SWICD_PayloadMessage::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RavenFCU_SWICD_PayloadMessage::data() const {
  // @@protoc_insertion_point(field_get:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.data)
  return _internal_data();
}
inline void RavenFCU_SWICD_PayloadMessage::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.data)
}
inline std::string* RavenFCU_SWICD_PayloadMessage::mutable_data() {
  // @@protoc_insertion_point(field_mutable:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.data)
  return _internal_mutable_data();
}
inline const std::string& RavenFCU_SWICD_PayloadMessage::_internal_data() const {
  return data_.Get();
}
inline void RavenFCU_SWICD_PayloadMessage::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RavenFCU_SWICD_PayloadMessage::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.data)
}
inline void RavenFCU_SWICD_PayloadMessage::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.data)
}
inline void RavenFCU_SWICD_PayloadMessage::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.data)
}
inline std::string* RavenFCU_SWICD_PayloadMessage::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RavenFCU_SWICD_PayloadMessage::release_data() {
  // @@protoc_insertion_point(field_release:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RavenFCU_SWICD_PayloadMessage::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace swicd
}  // namespace fcu
}  // namespace raven

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_payloadmessage_2eproto
