// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payloadmessage.proto

#include "payloadmessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace raven {
namespace fcu {
namespace swicd {
class RavenFCU_SWICD_PayloadMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RavenFCU_SWICD_PayloadMessage> _instance;
} _RavenFCU_SWICD_PayloadMessage_default_instance_;
}  // namespace swicd
}  // namespace fcu
}  // namespace raven
static void InitDefaultsscc_info_RavenFCU_SWICD_PayloadMessage_payloadmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::raven::fcu::swicd::_RavenFCU_SWICD_PayloadMessage_default_instance_;
    new (ptr) ::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RavenFCU_SWICD_PayloadMessage_payloadmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RavenFCU_SWICD_PayloadMessage_payloadmessage_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_payloadmessage_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_payloadmessage_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_payloadmessage_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_payloadmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage, messagesentts_),
  PROTOBUF_FIELD_OFFSET(::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage, messagereceivedts_),
  PROTOBUF_FIELD_OFFSET(::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage, data_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::raven::fcu::swicd::_RavenFCU_SWICD_PayloadMessage_default_instance_),
};

const char descriptor_table_protodef_payloadmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024payloadmessage.proto\022\017raven.fcu.swicd\""
  "_\n\035RavenFCU_SWICD_PayloadMessage\022\025\n\rmess"
  "ageSentTS\030\001 \001(\001\022\031\n\021messageReceivedTS\030\002 \001"
  "(\001\022\014\n\004data\030\003 \001(\014b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_payloadmessage_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_payloadmessage_2eproto_sccs[1] = {
  &scc_info_RavenFCU_SWICD_PayloadMessage_payloadmessage_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_payloadmessage_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_payloadmessage_2eproto = {
  false, false, descriptor_table_protodef_payloadmessage_2eproto, "payloadmessage.proto", 144,
  &descriptor_table_payloadmessage_2eproto_once, descriptor_table_payloadmessage_2eproto_sccs, descriptor_table_payloadmessage_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_payloadmessage_2eproto::offsets,
  file_level_metadata_payloadmessage_2eproto, 1, file_level_enum_descriptors_payloadmessage_2eproto, file_level_service_descriptors_payloadmessage_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_payloadmessage_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_payloadmessage_2eproto)), true);
namespace raven {
namespace fcu {
namespace swicd {

// ===================================================================

void RavenFCU_SWICD_PayloadMessage::InitAsDefaultInstance() {
}
class RavenFCU_SWICD_PayloadMessage::_Internal {
 public:
};

RavenFCU_SWICD_PayloadMessage::RavenFCU_SWICD_PayloadMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
}
RavenFCU_SWICD_PayloadMessage::RavenFCU_SWICD_PayloadMessage(const RavenFCU_SWICD_PayloadMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_data().empty()) {
    data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_data(),
      GetArena());
  }
  ::memcpy(&messagesentts_, &from.messagesentts_,
    static_cast<size_t>(reinterpret_cast<char*>(&messagereceivedts_) -
    reinterpret_cast<char*>(&messagesentts_)) + sizeof(messagereceivedts_));
  // @@protoc_insertion_point(copy_constructor:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
}

void RavenFCU_SWICD_PayloadMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RavenFCU_SWICD_PayloadMessage_payloadmessage_2eproto.base);
  data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&messagesentts_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&messagereceivedts_) -
      reinterpret_cast<char*>(&messagesentts_)) + sizeof(messagereceivedts_));
}

RavenFCU_SWICD_PayloadMessage::~RavenFCU_SWICD_PayloadMessage() {
  // @@protoc_insertion_point(destructor:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RavenFCU_SWICD_PayloadMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  data_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void RavenFCU_SWICD_PayloadMessage::ArenaDtor(void* object) {
  RavenFCU_SWICD_PayloadMessage* _this = reinterpret_cast< RavenFCU_SWICD_PayloadMessage* >(object);
  (void)_this;
}
void RavenFCU_SWICD_PayloadMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RavenFCU_SWICD_PayloadMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RavenFCU_SWICD_PayloadMessage& RavenFCU_SWICD_PayloadMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RavenFCU_SWICD_PayloadMessage_payloadmessage_2eproto.base);
  return *internal_default_instance();
}


void RavenFCU_SWICD_PayloadMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&messagesentts_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&messagereceivedts_) -
      reinterpret_cast<char*>(&messagesentts_)) + sizeof(messagereceivedts_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RavenFCU_SWICD_PayloadMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double messageSentTS = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          messagesentts_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double messageReceivedTS = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          messagereceivedts_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // bytes data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_data();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RavenFCU_SWICD_PayloadMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double messageSentTS = 1;
  if (!(this->messagesentts() <= 0 && this->messagesentts() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_messagesentts(), target);
  }

  // double messageReceivedTS = 2;
  if (!(this->messagereceivedts() <= 0 && this->messagereceivedts() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_messagereceivedts(), target);
  }

  // bytes data = 3;
  if (this->data().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  return target;
}

size_t RavenFCU_SWICD_PayloadMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 3;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // double messageSentTS = 1;
  if (!(this->messagesentts() <= 0 && this->messagesentts() >= 0)) {
    total_size += 1 + 8;
  }

  // double messageReceivedTS = 2;
  if (!(this->messagereceivedts() <= 0 && this->messagereceivedts() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RavenFCU_SWICD_PayloadMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const RavenFCU_SWICD_PayloadMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RavenFCU_SWICD_PayloadMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
    MergeFrom(*source);
  }
}

void RavenFCU_SWICD_PayloadMessage::MergeFrom(const RavenFCU_SWICD_PayloadMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.data().size() > 0) {
    _internal_set_data(from._internal_data());
  }
  if (!(from.messagesentts() <= 0 && from.messagesentts() >= 0)) {
    _internal_set_messagesentts(from._internal_messagesentts());
  }
  if (!(from.messagereceivedts() <= 0 && from.messagereceivedts() >= 0)) {
    _internal_set_messagereceivedts(from._internal_messagereceivedts());
  }
}

void RavenFCU_SWICD_PayloadMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RavenFCU_SWICD_PayloadMessage::CopyFrom(const RavenFCU_SWICD_PayloadMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:raven.fcu.swicd.RavenFCU_SWICD_PayloadMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RavenFCU_SWICD_PayloadMessage::IsInitialized() const {
  return true;
}

void RavenFCU_SWICD_PayloadMessage::InternalSwap(RavenFCU_SWICD_PayloadMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  data_.Swap(&other->data_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RavenFCU_SWICD_PayloadMessage, messagereceivedts_)
      + sizeof(RavenFCU_SWICD_PayloadMessage::messagereceivedts_)
      - PROTOBUF_FIELD_OFFSET(RavenFCU_SWICD_PayloadMessage, messagesentts_)>(
          reinterpret_cast<char*>(&messagesentts_),
          reinterpret_cast<char*>(&other->messagesentts_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RavenFCU_SWICD_PayloadMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace swicd
}  // namespace fcu
}  // namespace raven
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage* Arena::CreateMaybeMessage< ::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::raven::fcu::swicd::RavenFCU_SWICD_PayloadMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
